import { pgTable, uuid, varchar, text, integer, boolean, jsonb, timestamp } from 'drizzle-orm/pg-core';

export const fieldSections = pgTable('field_sections', {
  id: uuid('id').primaryKey().defaultRandom(),
  entityType: varchar('entity_type', { length: 255 }).notNull(),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  displayOrder: integer('display_order').notNull().default(0),
  isCollapsible: boolean('is_collapsible').notNull().default(false),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  createdBy: uuid('created_by'),
  updatedBy: uuid('updated_by'),
});

export const fieldDefinitions = pgTable('field_definitions', {
  id: uuid('id').primaryKey().defaultRandom(),
  entityType: varchar('entity_type', { length: 255 }).notNull(),
  sectionId: uuid('section_id').references(() => fieldSections.id),
  fieldKey: varchar('field_key', { length: 255 }).notNull(),
  label: varchar('label', { length: 255 }).notNull(),
  description: text('description'),
  dataType: varchar('data_type', { length: 50 }).notNull(),
  inputType: varchar('input_type', { length: 50 }).notNull(),
  defaultValue: text('default_value'),
  placeholder: varchar('placeholder', { length: 255 }),
  isRequired: boolean('is_required').notNull().default(false),
  isUnique: boolean('is_unique').notNull().default(false),
  isSearchable: boolean('is_searchable').notNull().default(false),
  isFilterable: boolean('is_filterable').notNull().default(false),
  isSortable: boolean('is_sortable').notNull().default(false),
  isVisible: boolean('is_visible').notNull().default(true),
  isEditable: boolean('is_editable').notNull().default(true),
  isReadOnly: boolean('is_read_only').notNull().default(false),
  validationRules: jsonb('validation_rules'),
  options: jsonb('options'),
  conditionalRules: jsonb('conditional_rules'),
  permissionRules: jsonb('permission_rules'),
  branchScope: jsonb('branch_scope'),
  displayOrder: integer('display_order').notNull().default(0),
  helpText: text('help_text'),
  isAuditEnabled: boolean('is_audit_enabled').notNull().default(false),
  isActive: boolean('is_active').notNull().default(true),
  version: integer('version').notNull().default(1),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  createdBy: uuid('created_by'),
  updatedBy: uuid('updated_by'),
});

export const fieldValues = pgTable('field_values', {
  id: uuid('id').primaryKey().defaultRandom(),
  entityType: varchar('entity_type', { length: 255 }).notNull(),
  entityId: uuid('entity_id').notNull(),
  fieldDefinitionId: uuid('field_definition_id').notNull().references(() => fieldDefinitions.id),
  textValue: text('text_value'),
  numberValue: integer('number_value'),
  dateValue: timestamp('date_value'),
  datetimeValue: timestamp('datetime_value'),
  booleanValue: boolean('boolean_value'),
  jsonValue: jsonb('json_value'),
  referenceType: varchar('reference_type', { length: 255 }),
  referenceId: uuid('reference_id'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  createdBy: uuid('created_by'),
  updatedBy: uuid('updated_by'),
});

export const fieldDefinitionAudit = pgTable('field_definition_audit', {
  id: uuid('id').primaryKey().defaultRandom(),
  fieldDefinitionId: uuid('field_definition_id').notNull(),
  action: varchar('action', { length: 50 }).notNull(),
  oldData: jsonb('old_data'),
  newData: jsonb('new_data'),
  changedBy: uuid('changed_by'),
  changedAt: timestamp('changed_at').notNull().defaultNow(),
});
