import { sql } from 'drizzle-orm';
import { db } from './src/database/connection.js';
import argon2 from 'argon2';
import { randomUUID } from 'crypto';

async function seed() {
  console.log('🌱 Starting Database Seeding...');
  
  try {
    const passwordHash = await argon2.hash('Admin123!');
    const userId = '1a0447dc-a550-45e4-a159-05c780a509f0';
    const roleId = randomUUID();
    const branchId = 'b356bd44-83ab-4145-9b06-6d5645cf7a60';
    const companyId = '4cd4d5ba-fc3e-4cec-8e2b-4e72924355fd';
    
    // Seed Users
    await db.execute(sql`
      INSERT INTO users (id, email, password_hash, status, is_mfa_enabled, created_at, updated_at)
      VALUES (${userId}, 'admin@rmn.edu.np', ${passwordHash}, 'ACTIVE', false, NOW(), NOW())
      ON CONFLICT (email) DO NOTHING;
    `);
    console.log('✅ Admin user created (admin@rmn.edu.np / Admin123!)');

    // Seed Permissions
    const permissions = [
      'person:read', 'person:write',
      'organization:read', 'organization:write',
      'student:read', 'student:write',
      'master-data:read', 'master-data:write',
      'finance:read', 'finance:write',
      'academics:read', 'academics:write',
      'hr:read', 'hr:write'
    ];
    
    for (const perm of permissions) {
      await db.execute(sql`
        INSERT INTO permissions (id, resource_action, description) 
        VALUES (gen_random_uuid(), ${perm}, 'Autogenerated permission')
        ON CONFLICT (resource_action) DO NOTHING;
      `);
    }
    console.log('✅ Permissions created');

    // Seed Roles & Role Permissions
    await db.execute(sql`
      INSERT INTO roles (id, name, is_system, created_at, updated_at)
      VALUES (${roleId}, 'Super Admin', true, NOW(), NOW())
      ON CONFLICT (name) DO NOTHING;
    `);
    
    await db.execute(sql`
      INSERT INTO role_permissions (role_id, permission_id)
      SELECT r.id, p.id FROM roles r, permissions p WHERE r.name = 'Super Admin'
      ON CONFLICT DO NOTHING;
    `);

    // Seed Organizations
    await db.execute(sql`
      INSERT INTO organizations (id, type, name, path, status, created_at, updated_at)
      VALUES (${companyId}, 'COMPANY', 'RMN Education Group', ${companyId}, 'ACTIVE', NOW(), NOW())
      ON CONFLICT (id) DO NOTHING;
    `);
    
    await db.execute(sql`
      INSERT INTO organizations (id, type, name, parent_id, path, status, created_at, updated_at)
      VALUES (${branchId}, 'BRANCH', 'Kathmandu Branch', ${companyId}, ${companyId || '.' || branchId}, 'ACTIVE', NOW(), NOW())
      ON CONFLICT (id) DO NOTHING;
    `);
    console.log('✅ Organizations created (Company & Branch)');

    // Assign Role to User
    await db.execute(sql`
      INSERT INTO user_roles (user_id, role_id, scope, branch_id)
      VALUES (${userId}, ${roleId}, 'GLOBAL', null)
      ON CONFLICT DO NOTHING;
    `);
    console.log('✅ Admin user assigned Super Admin role');

    // Numbering Policy for Students
    await db.execute(sql`
      INSERT INTO numbering_policies (id, entity_type, prefix, pattern, sequence_scope, is_gapless, is_active, created_at, updated_at)
      VALUES (gen_random_uuid(), 'STUDENT', 'STU', '{PREFIX}-{YEAR}-{SEQ:5}', 'YEARLY', true, true, NOW(), NOW())
      ON CONFLICT DO NOTHING;
    `);
    
    // Seed numbering sequence for current year
    await db.execute(sql`
      INSERT INTO numbering_sequences (id, policy_id, scope_key, current_value, created_at, updated_at)
      SELECT gen_random_uuid(), id, 'YEAR_' || EXTRACT(YEAR FROM CURRENT_DATE), 0, NOW(), NOW()
      FROM numbering_policies WHERE entity_type = 'STUDENT'
      ON CONFLICT DO NOTHING;
    `);
    console.log('✅ Numbering Policy for STUDENT initialized');

    console.log('🎉 Seeding Complete!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

seed();
